# Generated by Django 5.1.4 on 2026-01-05 15:35

import ideas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0002_alter_devtool_id_alter_idea_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="image",
            field=models.ImageField(blank=True, upload_to=ideas.models.idea_image_path),
        ),
    ]
